version: "3.8"
services:
  common-backend:
    build:
      context: ../
      dockerfile: Dockerfile
    command: sh /scripts/scan.sh
    environment:
      - SERVICE=fantasy-baseball-common-backend
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - SONAR_TOKEN=${SONAR_TOKEN}
    volumes:
      - ../:/app/
