version: "3.8"
services:
  api:
    build:
      context: ../
      dockerfile: Dockerfile
      target: ci
    command: sh /scripts/scan.sh
    depends_on:
      database:
        condition: service_healthy
    environment:
      - SERVICE=fantasy-baseball-common-backend
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - SONAR_TOKEN=${SONAR_TOKEN}
    volumes:
      - ../:/app/
