version: "3.8"
services:
  common-backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: ci
    restart: always
    command: sleep infinity
    environment:
      - SERVICE=fantasy-baseball-common-backend
